config/routes.rb
Rails.application.routes.draw do
#  resources :store_items

  resources :stores do
    resources :items, only: [:show, :index, :new]
  end

  resources :lists do
    resources :stores, only: [:index, :show ]
  end
  resources :items
  resources :users
  resources :list_items


  root 'application#hello'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :list_items
  has_many :items, through: :list_items

  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true

  validates_associated :list_items
  accepts_nested_attributes_for :list_items


  def list_items_attributes=(list_items_attributes)
    list_items_attributes.values.each do |list_item_attribute|
      @list_item = self.list_items.find(list_item_attribute[:id])
      @list_item.update_column(:quantity, list_item_attribute[:quantity])
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :require_logged_in
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = current_user.lists
  end

  def new
    @list = List.new
  end

  def create
    @list = current_user.lists.build(list_params)
    if @list.save
      render json: @list
    else
      render new_list_path
    end
  end

  def show

  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list)
    else
      redirect_to edit_list_path(@list)
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :description, item_ids:[], list_items_attributes:[:quantity, :id])
  end

  def set_list
    @list = List.find(params[:id])
    @list.user_id === current_user.id
  end

  def require_logged_in
     return head(:forbidden) unless logged_in?
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_list.html.erb
<%= form_for(@list) do |f|%>
<div><%= f.label :name %><br>
<%= f.text_field :name %></div>

<div><%= f.label :description %><br>
<%= f.text_area :description %></div>

<div>
  <label>Items</label><br>
  <%= f.collection_check_boxes :item_ids, Item.all, :id, :name %>
</div>

<div> <%= f.submit %> </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing Lists</h1>

<%= render 'list' %>

<%= link_to 'Show', list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1> Here's all your lists so far </h1>
<% @lists.each do |list| %>
<li><%= link_to list.name, list_path(list) %> - <%= link_to 'Delete this List', list_path(list), :method => "delete" %> </li>
<% end %>

  <p><%= link_to "Back to profile", root_path %>
  <p><%= link_to "Make a new list", new_list_path %></p>

app/views/lists/new.html.erb
<h1> Make your New Grocery List here </h1>
<% if @list.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@list.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @list.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>

<% end %>
<%= render 'list' %>
<div id="list">

</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<h2><%= @list.description %> </h2>

<% if @list.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@list.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @list.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% @list.list_items.each do |item| %>
<% if item.errors[:quantity].any? %>
<ul>
  <% @list.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  <% end %>
  <% end %>
</ul>

<%= form_for @list  do |f| %>
<% @list.list_items.each do |item| %>
  <li><%= link_to item.item.name, item_path(item.item) if item.item_id != nil%>
    <%= f.label :quantity%>
    <%= f.fields_for :list_items, item do |list_item|%>
      <%= list_item.text_field :quantity, :value=>item.quantity %>
      <% end %>
    </li>
<% end %>
<%= f.submit %>
<% end %>


<label> Check out Prices at these stores:</label>
<%= form_tag(list_store_path(@list), method: "get") do %>
<%= collection_select :store, :id, Store.all, :id, :name %>
<%= submit_tag "Filter" %>
<% end %>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>