config/routes.rb
Rails.application.routes.draw do
#  resources :store_items

  resources :stores do
    resources :items, only: [:show, :index, :new]
  end

  resources :lists do
    resources :stores, only: [:index, :show ]
  end
  resources :items
  resources :users
  resources :list_items


  root 'application#hello'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :store_items
  has_many :items, through: :store_items


  def items_high_to_low
    self.store_items.order(price: :desc)
  end

  def items_low_to_high
    self.store_items.order(price: :asc)
  end


end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show]

  def index
    @stores = Store.all
  end

  def show
    if !params[:sort_order].blank?
      if params[:sort_order] == "High to Low"
        @store_items  = @store.items_high_to_low
      elsif params[:sort_order] == "Low to High"
        @store_items = @store.items_low_to_high
      end
      @sort_order = params[:sort_order]
    elsif !params[:list_id].blank?
      @store = Store.find(params[:store][:id])
      @list = List.find(params[:list_id])
      list_items = @list.items.all.map {|item| item.name}
      store_items = @store.store_items.all
      @store_items =store_items.map {|items| items if list_items.include?(items.item.name)}.compact
      else
        @store_items = @store.store_items
    end
  end

  private
  def set_store
    @store = Store.find(params[:id])
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/index.html.erb
<h1> Stores </h1>
<% @stores.each do |store| %>
<ul>
  <li><%= link_to store.name, store_path(store) %> </li>
</ul>

<%end%>

app/views/stores/show.html.erb
<h1><%= @store.name %></h1>
<h2>Location: <%= @store.description %>

<h3>Here are the items sold at this store </h3>
<div>
  <h3>Filter Items:</h3>
  <%= form_tag(store_path, method: "get") do %>
    <%= select_tag "sort_order", options_for_select(["High to Low", "Low to High"], @sort_order), :prompt => "Please select" %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>
<div><% @store_items.each do |items| %>
<li>
  <%= link_to items.item.name, item_path(items.item) %> - <label>Price:</label><%=items.price %>
</li>
<% end %>
</div>

<div>
  <p><%= link_to 'Add New Item to Store', new_store_item_path(@store)%> </p>
</div>


<div>
  <p><%= link_to 'Back to Store List', stores_path %></p>
</div>