config/routes.rb
Rails.application.routes.draw do
#  resources :store_items

  resources :stores do
    resources :items, only: [:show, :index, :new]
  end

  resources :lists do
    resources :stores, only: [:index, :show ]
  end
  resources :items
  resources :users
  resources :list_items


  root 'application#hello'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :list_items
  has_many :lists, through: :list_items

  has_many :store_items
  has_many :stores, through: :store_items

  validates :name, presence: true
  validates :description, presence: true
  validates :department, presence: true
  validates_associated :store_items

  accepts_nested_attributes_for :store_items

# scope :produce_department, -> { where(department: 'Produce') }
# scope :deli_department, -> { where(department: 'Deli') }
# scope :frozen_department, -> { where(department: 'Frozen') }
# scope :dairy_department, -> { where(department: 'Dairy') }
# scope :baby_department, -> { where(department: 'Baby') }
# scope :misc_department, -> { where(department: 'Miscellaneous') }


 def self.departments
   select(:department).distinct
 end

 def self.departments_by_name
   departments.map {|item| item.department}
 end

 def self.sort_by_department(department)
  where("department = ?", department)
 end

 def store_items_attributes=(store_item_attributes)
      store_item_attributes.values.each do |store_item_attribute|
        self.store_items.build(store_item_attribute)
      end
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show]

  def index
    if !params[:store_id].blank?
      store_items = Store.find(params[:store_id]).store_items
      @items = store_items.map {|item| item.item}.uniq
    elsif !params[:sort_by_department].blank?
      @items = Item.sort_by_department(params[:sort_by_department])
      @department = params[:sort_by_department]
    else
      @items = Item.all
      respond_to do |format|
        format.json { render :json=>@items}
        format.html {render :index }
      end
    end
  end

  def show
    if !params[:store_id].blank?
      @store = Store.find(params[:store_id])
    end
      respond_to do |format|
      format.html { render :show}
      format.json { render json: @item }
      end
  end

  def new
    if !params[:store_id].blank?
      @store = Store.find(params[:store_id])
    end
      @item = Item.new
  end

  def create
    if !params[:item][:store_items_attributes].blank?
      @item = Item.new(item_params)
      @store = Store.find(params[:item][:store_items_attributes]["0"][:store_id])
      if @item.save
        redirect_to store_item_path(@store, @item)
      else
        redirect_to new_store_item_path(@store)
      end
    else
    @item = Item.new(item_params)
    if @item.save
      redirect_to item_path(@item)
    else
      render new_item_path
    end
  end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :department, store_items_attributes: [:store_id, :price])
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_product.html.erb
<h3><%= product.id%>:<%=product.name %> </h3>
<div id= "description-<%=product.id%>"><%= truncate product.description %></div>
<div id="inventory-<%=product.id%>"></div>
<button class="js-more" data-id="<%= product.id %>">More Info...</button>

app/views/items/index.html.erb
<%= form_tag(items_path, method: "get") do %>
  <%= select_tag "sort_by_department", options_for_select(Item.departments_by_name, @department), :prompt => "Please select"%>
  <%= submit_tag "Filter" %>
<% end %>

<% @items.each do |item| %>
<li>
  <%= link_to item.name, item_path(item) %>
</li>
<% end %>


<div>
  <p>
    <%= link_to 'Add a New Item', new_item_path %>
  </p></div>

app/views/items/new.html.erb
<h1> Creating a New Item <%= link_to @store.name, store_path(@store) if @store %></h1>

<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@item.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@item) do |f| %>
<div><%= f.label :name %><br>
<%= f.text_field :name %></div>

<div><%= f.label :description %><br>
<%= f.text_area :description %></div>

<div><%= f.label :department %><br>
<%= f.text_field :department, list: 'department' %><br>
  <datalist id="department">
      <% Item.departments.each do |item| %>
        <option value="<%= item.department %>"></option>
      <% end %>
    </datalist>
</div>
<div>
  <% if @store %>
  <%= f.fields_for :store_items, @item.store_items.build do |store_item|%>
  <%= f.label :price  %><br>
  <%= store_item.hidden_field :store_id, :value=>@store.id %>
  <%= store_item.text_field :price %>
  <% end %>
  <%end%>
</div>
    <%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1 class="itemName"><%= @item.name %></h1>
<div>
  <a href="#" class="js-next" data-id="<%=@item.id%>">Next...</a>
<p class="itemDescription"><%= @item.description %> <br>
</p>
</div>

<% if @store %>
<p>
<h3> Available @ <%= link_to @store.name, store_path(@store)%></h3>
<h3> Here is a list of all available items @<%= link_to @store.name, store_items_path(@store) %>
</p>
<% end %>

<div>

<p> <%= link_to "Back to Items", items_path %> </p>
</div>