config/routes.rb
Rails.application.routes.draw do
#  resources :store_items

  resources :stores do
    resources :items, only: [:show, :index, :new]
  end

  resources :lists do
    resources :stores, only: [:index, :show ]
  end
  resources :items
  resources :users
  resources :list_items


  root 'application#hello'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroceryListApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1> Welcome to Grocery List App </h1>
    <% if logged_in? %>
    <h3><a href="#" class="user_info" data-id="<%=current_user.id%>"><%= "Hello, #{current_user.name}!" %></h3>
    <h3><%= link_to "Lists", lists_path %></h3>
    <h3><%= link_to "Stores", stores_path %></h3>
    <h3><a class="items-index" href="#" >Items</a></h3>
    <h3><%= link_to "Log Out", logout_path, method: :delete %></h3>
    <% else %>
    <h3><%= link_to "Sign In", login_path %></h3>
    <h3><%= link_to "Sign Up", new_user_path %></h3>
    <% end %>
    <div id="items">

    </div>
    <a href="#" class="sort-items">Sort Items Alphabetically </a>
    <div id="user_info">
    </div>
    <div id="lists"></div>
    <%= yield %>

  </body>

</html>